all:
	@make clean
	@make -C goplug-fail
	@make -C goplug-minimal
	@make -C goplug-helloworld
	@make -C goplug-openweathermap
	@make -C goplug-quote
	@make -C goplug-simple

clean:
	@make -C goplug-fail clean
	@make -C goplug-minimal clean
	@make -C goplug-helloworld clean
	@make -C goplug-openweathermap clean
	@make -C goplug-quote clean
	@make -C goplug-simple clean
